name: /home/vejvar-martin-nj/git/picard/.conda
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.8=py310hf71b8c6_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.29.0=pyh707e725_0
  - jedi=0.19.2=pyhff2d567_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.47.0=hadc24fc_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.5=he02047a_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - promise=2.3=py310hff52083_9
  - prompt-toolkit=3.0.48=pyha770c72_0
  - psutil=6.1.0=py310ha75aee5_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.10.15=h4a871b0_2_cpython
  - python_abi=3.10=2_cp310
  - pyzmq=26.2.0=py310h71f11fc_3
  - readline=8.2=h8228510_1
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.47.0=h9eae976_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4.1=py310ha75aee5_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h3b0a872_6
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - pip:
      - about-time==3.1.1
      - accelerate==1.6.0
      - aiohttp==3.8.1
      - aiosignal==1.2.0
      - alive-progress==2.3.1
      - anyio==3.5.0
      - asgiref==3.5.0
      - async-timeout==4.0.2
      - attrs==21.4.0
      - autopep8==1.6.0
      - black==22.1.0
      - certifi==2021.10.8
      - charset-normalizer==2.0.12
      - click==8.0.4
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==0.29.28
      - datasets==3.2.0
      - dill==0.3.4
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - et-xmlfile==2.0.0
      - evaluate==0.2.2
      - fastapi==0.74.1
      - filelock==3.6.0
      - flake8==4.0.1
      - fonttools==4.56.0
      - frozenlist==1.3.0
      - fsspec==2024.9.0
      - gitdb==4.0.9
      - gitpython==3.1.27
      - grapheme==0.6.0
      - h11==0.13.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - idna==3.3
      - iniconfig==1.1.1
      - ipywidgets==8.1.5
      - isort==5.10.1
      - jinja2==3.1.6
      - jiter==0.9.0
      - joblib==1.1.0
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mccabe==0.6.1
      - mpmath==1.3.0
      - multidict==6.0.2
      - multiprocess==0.70.12.2
      - mypy==0.931
      - mypy-extensions==0.4.3
      - neo4j==5.27.0
      - networkx==3.4.2
      - nltk==3.7
      - numpy==2.2.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.68.2
      - openpyxl==3.1.5
      - oxrdflib==0.4.0
      - pandas==2.2.3
      - pathspec==0.9.0
      - pathtools==0.1.2
      - pillow==9.0.1
      - pip==24.3.1
      - platformdirs==4.0.0
      - pluggy==1.0.0
      - protobuf==3.19.4
      - py==1.11.0
      - pyarrow==19.0.0
      - pycodestyle==2.8.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyflakes==2.4.0
      - pyoxigraph==0.4.4
      - pyparsing==3.0.7
      - pytest==7.0.1
      - pytest-check==1.0.4
      - python-dateutil==2.8.2
      - pytz==2021.3
      - pyyaml==6.0
      - rapidfuzz==3.12.2
      - rdflib==7.1.1
      - regex==2022.3.2
      - requests==2.32.3
      - responses==0.18.0
      - sacremoses==0.0.47
      - safetensors==0.4.5
      - seaborn==0.13.2
      - sentencepiece==0.1.96
      - sentry-sdk==2.20.0
      - setproctitle==1.2.2
      - setuptools==75.4.0
      - shortuuid==1.0.8
      - smmap==5.0.0
      - sniffio==1.2.0
      - sparqlwrapper==2.0.0
      - sqlparse==0.4.2
      - starlette==0.17.1
      - sympy==1.13.1
      - tenacity==8.0.1
      - termcolor==1.1.0
      - tokenizers==0.21.1
      - toml==0.10.2
      - tomli==2.0.1
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.17.0
      - triton==3.2.0
      - typing-extensions==4.7.1
      - tzdata==2025.2
      - urllib3==2.3.0
      - uvicorn==0.17.5
      - wandb==0.19.6
      - widgetsnbextension==4.0.13
      - xlsxwriter==3.2.1
      - xxhash==3.0.0
      - yarl==1.7.2
      - yaspin==2.1.0
prefix: /home/vejvar-martin-nj/git/picard/.conda
